using System.Collections.Generic;
/*
 * This file would be used if we converted to use the Entity Framework
 */

/*
* Commented to compile because the model would be generated by the Entity Framework
*/
namespace StudentForYou.DB.Interfaces
{
    /*public interface ICoursesDB : IEntityFrameworkDB<Course>
    {
        List<Course> GetCourses();
        Course GetCourse(int id);
        void PostCourse(Course course);
    }*/

}
