//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentForYou.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class chat_group
    {
        public int chg_id { get; set; }
        public int chg_user_id { get; set; }
        public int chg_course_id { get; set; }
        public string chg_text { get; set; }
        public System.DateTime chg_creation_date { get; set; }
    }
}
