//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentForYou.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int com_id { get; set; }
        public int com_user_id { get; set; }
        public string com_text { get; set; }
        public System.DateTime com_creation_date { get; set; }
        public int com_qns_id { get; set; }
        public int com_likes { get; set; }
    }
}
