//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentForYou.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class courses_reviews
    {
        public int cor_id { get; set; }
        public int cor_cou_id { get; set; }
        public int cor_user_id { get; set; }
        public string cor_text { get; set; }
        public System.DateTime cor_creation_date { get; set; }
    }
}
