//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentForYou.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class courses_files
    {
        public int file_id { get; set; }
        public byte[] file { get; set; }
        public string file_name { get; set; }
        public int file_cou_id { get; set; }
        public int file_user_id { get; set; }
        public System.DateTime file_creation_date { get; set; }
    }
}
