//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentForYou.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class courses
    {
        public int cou_id { get; set; }
        public string cou_name { get; set; }
        public int cou_difficulty { get; set; }
        public string cou_description { get; set; }
        public System.DateTime cou_creation_date { get; set; }
    }
}
