//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentForYou.DB
{
    using Microsoft.EntityFrameworkCore;
    //using System.Data.Entity;

    public partial class StudentForYouEntities : DbContext
    {
        public StudentForYouEntities(DbContextOptions<StudentForYouEntities> options)
            : base(options)
        {
        }

        public virtual DbSet<GroupMessage> chat_group { get; set; }
        public virtual DbSet<PersonalChat> chat_personal { get; set; }
        public virtual DbSet<Comment> comments { get; set; }
        public virtual DbSet<Course> courses { get; set; }
        public virtual DbSet<CourseFile> courses_files { get; set; }
        public virtual DbSet<Review> courses_reviews { get; set; }
        public virtual DbSet<Question> questions { get; set; }
        public virtual DbSet<User> users { get; set; }
    }
}
