using System.Collections.Generic;
/*
 * This file would be used if we converted to use the Entity Framework
 */

/*
* Commented to compile because the context would be generated by the Entity Framework
*/
namespace StudentForYou.DB
{
    public class EntityFrameworkDB<T> : IEntityFrameworkDB<T> where T : class
    {
        
        //private StudentForYouContext _db;

        public EntityFrameworkDB( /*StudentForYouContext context*/)
        {
           // _db = context;
        }

        public IEnumerable<T> GetModelList()
        {
            //return _db.Set<T>().AsNoTracking();
            return null;
        }

        public T GetModelByID(int id)
        {
            //return _db.Set<T>().Find(id);
            return null;
        }

        public void InsertModel(T model)
        {
            //_db.Set<T>().Add(model);
        }

        public void DeleteModel(int id)
        {
            //var entity = GetModelByID(id);
            //_db.Set<T>().Remove(entity);
        }

        public void UpdateModel(T model)
        {
           // _db.Set<T>().Update(model);
        }

        public void Save()
        {
            //_db.SaveChanges();
        }
    }
}
